export const IS_OPEN_WINDOW_TOGGLE = 'IS_OPEN_WINDOW_TOGGLE';

export const COMPOSITIONS_GET_REQUEST = 'COMPOSITIONS_GET_REQUEST';
export const COMPOSITIONS_GET_SUCCESS = 'COMPOSITIONS_GET_SUCCESS';
export const COMPOSITIONS_GET_FAILURE = 'COMPOSITIONS_GET_FAILURE';
